# Generated by Django 3.1.1 on 2020-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_date', models.DateField(null=True)),
                ('creator', models.CharField(max_length=250)),
                ('last_maj', models.DateField(null=True)),
                ('version', models.CharField(max_length=250)),
                ('mod_type', models.CharField(max_length=250)),
                ('download', models.TextField()),
            ],
        ),
    ]
