# Generated by Django 3.1.1 on 2020-10-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_auto_20201008_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(default='', max_length=2083, unique=True)),
                ('published', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TheodoTeam',
        ),
    ]
