# Generated by Django 3.1.1 on 2020-10-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0003_auto_20201008_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creator', models.CharField(default='', max_length=2083, unique=True)),
                ('created_date', models.DateTimeField()),
                ('last_maj', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('download', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('img', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
