# Generated by Django 3.1.1 on 2020-10-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0006_auto_20201015_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mods',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
