# Generated by Django 3.1.1 on 2020-10-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('creator', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('version', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('download', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('img', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
