# Generated by Django 3.1.1 on 2020-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheodoTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('fun_fact', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mods',
        ),
    ]
